### ISSUE TITLE
FEAT REQUEST: Canary Runtimes are deprecated. Request to update runtime and add validation to variables for acceptable runtimes.

### ISSUE THREAD

**Issue by LuishXY** [aws-samples/cloudwatch-synthetics-canary-terraform#1]
Hi, 
I'd love to contribute to this project by updating the runtimes and adding validation logic to the variables in the canary module.

**Comment by marjet26** [comment]
Hello @LuishXY , 

Please please feel free to fork this project and create a pull request with the changes.

**Comment by marjet26** [comment]
Runtime updated.
